import { EXECS_22_23, EXECS_23_24, EXECS_24_25 } from 'assets/about/executives';

const BUTTONS = ['All', 'Core', 'Events', 'External', 'F&B', 'Marketing'];

const VISION_MISSION = [
	{
		vision: 'Diverse and Inclusive Community',
		mission: `We aim to create an Indonesian club at UBC that embraces diversity, respects individual identities,
			and celebrates Indonesian culture, fostering a sense of belonging for all members.`,
	},
	{
		vision: 'Fun and Engaging Activities',
		mission: `We aim to organize a variety of recreational and cultural events, 
		social gatherings, and outings that cater to diverse interests, 
		ensuring members have enjoyable experiences and create lasting memories.`,
	},
	{
		vision: "Members' Career Development",
		mission: `We aim to provide resources, workshops, and networking opportunities to 
			support our members in their academic and professional growth, equipping 
			them with skills, connections, and guidance for successful career paths.`,
	},
];

const EXECUTIVES = {
	'2024/2025': {
		Core: [
			{
				name: 'Justin Wibowo',
				position: 'President',
				department: 'Core',
				image: EXECS_24_25[0],
				education: '4th Year LFS',
			},
			{
				name: 'Christella Khosasih',
				position: 'Vice President',
				department: 'Core',
				image: EXECS_24_25[1],
				education: '4th Year LFS',
			},
			{
				name: 'Rafael Roswell',
				position: 'Treasurer',
				department: 'Core',
				image: EXECS_24_25[2],
				education: '3rd Year Commerce',
			},
			{
				name: 'Valencia Gabrielle Hartono',
				position: 'Secretary',
				department: 'Core',
				image: EXECS_24_25[3],
				education: '4th Year Commerce',
			},
		],
		Events: [
			{
				name: 'Aiko Josephine Sumarno',
				position: 'Events Director',
				department: 'Events',
				image: EXECS_24_25[4],
				education: '2nd Year Science',
			},
			{
				name: 'Wilbert Kawira',
				position: 'Logistics Director',
				department: 'Events',
				image: EXECS_24_25[5],
				education: '2nd Year LFS',
			},
			{
				name: 'Bradley Eugene Sakran',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_24_25[6],
				education: '2nd Year Science',
			},
			{
				name: 'Dion Raphael Sunotoredjo',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_24_25[7],
				education: '2nd Year Commerce',
			},
			{
				name: 'Tiffany Hersa',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_24_25[8],
				education: '1st Year Commerce',
			},
		],
		External: [
			{
				name: 'Nathania Rei',
				position: 'Outreach Director',
				department: 'External',
				image: EXECS_24_25[9],
				education: '3rd Year Arts',
			},
			{
				name: 'Anabel Iris Eliora Hartanto',
				position: 'Sponsorship Director',
				department: 'External',
				image: EXECS_24_25[10],
				education: '2nd Year Arts',
			},
			{
				name: 'Vanessa Arianto',
				position: 'Sponsorship Coordinator',
				department: 'External',
				image: EXECS_24_25[11],
				education: '4th Year LFS',
			},
			{
				name: 'Gabriella Aiko',
				position: 'Sponsorship Coordinator',
				department: 'External',
				image: EXECS_24_25[12],
				education: '2nd Year Applied Science',
			},
		],
		'F&B': [
			{
				name: 'Ann Yumi Kawanto',
				position: 'F&B Director',
				department: 'Food & Beverage',
				image: EXECS_24_25[13],
				education: '3rd Year LFS',
			},
			{
				name: 'Audri Silvi Orinko',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_24_25[14],
				education: '2nd Year LFS',
			},
			{
				name: 'Adrian Nicholas Hasjim',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_24_25[15],
				education: '2nd Year Science',
			},
			{
				name: 'Trigo Prawira',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_24_25[16],
				education: '2nd Year Commerce',
			},
		],
		Marketing: [
			{
				name: 'Adni Sadhira Dharmakusuma',
				position: 'Marketing Director',
				department: 'Marketing',
				image: EXECS_24_25[17],
				education: '2nd Year Arts',
			},
			{
				name: 'Angelina Alimin',
				position: 'Creative Director',
				department: 'Marketing',
				image: EXECS_24_25[18],
				education: '3rd Year Commerce',
			},
			{
				name: 'Marie Samantha Fidelia',
				position: 'Webmaster Lead',
				department: 'Marketing',
				image: EXECS_24_25[19],
				education: '3rd Year Science',
			},
			{
				name: 'Accitadevi Mangala Ongko',
				position: 'Content Creator',
				department: 'Marketing',
				image: EXECS_24_25[20],
				education: '2nd Year Commerce',
			},
			{
				name: 'Latascha Hartarto',
				position: 'Content Creator',
				department: 'Marketing',
				image: EXECS_24_25[21],
				education: '1st Year Arts',
			},
			{
				name: 'Angelica Eileen Indarto',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_24_25[22],
				education: '2nd Year Arts',
			},
			{
				name: 'Brenda Gunawan',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_24_25[23],
				education: '3rd Year Arts',
			},
			{
				name: 'Ray Danavaro Tandjung',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_24_25[24],
				education: '1st Year Arts',
			},
			{
				name: 'Jessie Megan',
				position: 'UX Designer',
				department: 'Marketing',
				image: EXECS_24_25[25],
				education: '3rd Year Science',
			},
			{
				name: 'Matthew Andersen Haryanto',
				position: 'Webmaster',
				department: 'Marketing',
				image: EXECS_24_25[26],
				education: '2nd Year Science',
			},
			{
				name: 'Jennifer Saphira Evani Tjen',
				position: 'Media Coordinator',
				department: 'Marketing',
				image: EXECS_24_25[27],
				education: '2nd Year Science',
			},
		],
	},
	'2023/2024': {
		Core: [
			{
				name: 'Imelda Alimin',
				position: 'President',
				department: 'Core',
				image: EXECS_23_24[0],
				education: '4th Year Commerce',
			},
			{
				name: 'Nadya Rei',
				position: 'Vice President',
				department: 'Core',
				image: EXECS_23_24[1],
				education: '3rd Year LFS',
			},
			{
				name: 'Joanico Huang',
				position: 'Treasurer',
				department: 'Core',
				image: EXECS_23_24[2],
				education: '2nd Year Commerce',
			},
			{
				name: 'Jade Tjandra',
				position: 'Secretary',
				department: 'Core',
				image: EXECS_23_24[3],
				education: '4th Year LFS',
			},
		],
		Events: [
			{
				name: 'Kent Jose',
				position: 'Events Director',
				department: 'Events',
				image: EXECS_23_24[4],
				education: '2nd Year Arts',
			},
			{
				name: 'Justin Wibowo',
				position: 'Logistics Director',
				department: 'Events',
				image: EXECS_23_24[5],
				education: '2nd Year LFS',
			},
			{
				name: 'Christella Khosasih',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_23_24[6],
				education: '3rd Year LFS',
			},
			{
				name: 'Nathania Rei',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_23_24[7],
				education: '2nd Year Arts',
			},
			{
				name: 'Anabel Hartanto',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_23_24[8],
				education: '1st Year Arts',
			},
		],
		External: [
			{
				name: 'Findytia Viandra',
				position: 'Outreach Director',
				department: 'External',
				image: EXECS_23_24[9],
				education: '3rd Year Arts',
			},
			{
				name: 'Kihana Sasha',
				position: 'Corporate Relations Director',
				department: 'External',
				image: EXECS_23_24[10],
				education: '3rd Year Arts',
			},
			{
				name: 'Charlene Suryadi',
				position: 'Sponsorship Coordinator',
				department: 'External',
				image: EXECS_23_24[11],
				education: '3rd Year LFS',
			},
		],
		'F&B': [
			{
				name: 'Richelle Tan',
				position: 'F&B Director',
				department: 'Food & Beverage',
				image: EXECS_23_24[13],
				education: '2nd Year Arts',
			},
			{
				name: 'Rafael Roswell',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_23_24[14],
				education: '2nd Year Commerce',
			},
			{
				name: 'Ann Yumi',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_23_24[15],
				education: '2nd Year LFS',
			},
			{
				name: 'Wilbert Kawira',
				position: 'F&B Coordinator',
				department: 'Food & Beverage',
				image: EXECS_23_24[16],
				education: '1st Year LFS',
			},
		],
		Marketing: [
			{
				name: 'Michelle TjondroSuharto',
				position: 'Marketing Director',
				department: 'Marketing',
				image: EXECS_23_24[17],
				education: '3rd Year Commerce',
			},
			{
				name: 'Tavaella Gozali',
				position: 'Creative Director',
				department: 'Marketing',
				image: EXECS_23_24[18],
				education: '2nd Year LFS',
			},
			{
				name: 'Christopher Hadrian',
				position: 'Webmaster Lead',
				department: 'Marketing',
				image: EXECS_23_24[19],
				education: '4th Year Science',
			},
			{
				name: 'Luna Tedjokusumo',
				position: 'Content Creator',
				department: 'Marketing',
				image: EXECS_23_24[20],
				education: '3rd Year Applied Science',
			},
			{
				name: 'Jessie Megan',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_23_24[21],
				education: '2nd Year Science',
			},
			{
				name: 'Marie Samantha',
				position: 'Web Developer',
				department: 'Marketing',
				image: EXECS_23_24[22],
				education: '2nd Year Science',
			},
			{
				name: 'Dhira Dharmakusuma',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_23_24[23],
				education: '1st Year Arts',
			},
			{
				name: 'Angelina Alimin',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_23_24[24],
				education: '2nd Year Commerce',
			},
			{
				name: 'Shannon Aurelia',
				position: 'Content Creator',
				department: 'Marketing',
				image: EXECS_23_24[25],
				education: '2nd Year Science',
			},
		],
	},
	'2022/2023': {
		Core: [
			{
				name: 'Louistrycia Kho',
				position: 'President',
				department: 'Core',
				image: EXECS_22_23[15],
				education: '4th Year LFS',
			},
			{
				name: 'Iervinny Tanto',
				position: 'Vice President',
				department: 'Core',
				image: EXECS_22_23[4],
				education: '4th Year Commerce',
			},
			{
				name: 'Ian Christiawan',
				position: 'Treasurer',
				department: 'Core',
				image: EXECS_22_23[3],
				education: '3rd Year Commerce',
			},
			{
				name: 'Josephine Valyne',
				position: 'Secretary',
				department: 'Core',
				image: EXECS_22_23[10],
				education: '3rd Year Arts',
			},
			{
				name: 'Russell William Sumarno',
				position: 'Internal',
				department: 'Core',
				image: EXECS_22_23[22],
				education: '3rd Year Applied Science ',
			},
		],
		Events: [
			{
				name: 'Kihana Sasha',
				position: 'Events Director',
				department: 'Events',
				image: EXECS_22_23[14],
				education: '2nd Year Arts',
			},
			{
				name: 'Sidney Lukito',
				position: 'Events Director',
				department: 'Events',
				image: EXECS_22_23[23],
				education: '2nd Year Commerce',
			},
			{
				name: 'Findytia Viandra',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_22_23[2],
				education: '2nd Year Arts',
			},
			{
				name: 'Jade Tjandra',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_22_23[6],
				education: '3rd Year LFS',
			},
			{
				name: 'Joanico Huang',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_22_23[8],
				education: '1st Year Commerce',
			},
			{
				name: 'Jonathan Santoso',
				position: 'Events Coordinator',
				department: 'Events',
				image: EXECS_22_23[9],
				education: '2nd Year Commerce',
			},
		],
		External: [
			{
				name: 'Nadya Rei',
				position: 'Corporate Relations Director',
				department: 'External',
				image: EXECS_22_23[18],
				education: '2nd Year LFS',
			},
			{
				name: 'Kent Jose',
				position: 'Sponsorship Coordinator',
				department: 'External',
				image: EXECS_22_23[13],
				education: '1st Year Arts',
			},
			{
				name: 'Vincent Danyo',
				position: 'Sponsorship Coordinator',
				department: 'External',
				image: EXECS_22_23[25],
				education: '3rd Year LFS',
			},
			{
				name: 'Rachel Tandjung',
				position: 'Outreach Director',
				department: 'External',
				image: EXECS_22_23[20],
				education: '4th Year Commerce',
			},
		],
		'F&B': [
			{
				name: 'Luna Tedjokusumo',
				position: 'F&B Director',
				department: 'F&B',
				image: EXECS_22_23[16],
				education: '2nd Year Applied Science',
			},
			{
				name: 'Christella Khosasih ',
				position: 'F&B Coordinator',
				department: 'F&B',
				image: EXECS_22_23[0],
				education: '2nd Year LFS ',
			},
			{
				name: 'Fernando Axel',
				position: 'F&B Coordinator',
				department: 'F&B',
				image: EXECS_22_23[19],
				education: '4th Year Commerce',
			},
		],
		Marketing: [
			{
				name: 'Kelly Milana Widjaja',
				position: 'Marketing Director',
				department: 'Marketing',
				image: EXECS_22_23[12],
				education: '4th Year LFS',
			},
			{
				name: 'Imelda Alimin',
				position: 'Creative Director',
				department: 'Marketing',
				image: EXECS_22_23[5],
				education: '3rd Year Commerce',
			},
			{
				name: 'Tavaella Gozali',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_22_23[24],
				education: '1st Year LFS',
			},
			{
				name: 'Richelle Tan',
				position: 'Creative Coordinator',
				department: 'Marketing',
				image: EXECS_22_23[21],
				education: '1st Year Arts',
			},
			{
				name: 'Michelle TjondroSuharto ',
				position: 'Content Creator',
				department: 'Marketing',
				image: EXECS_22_23[17],
				education: '2nd Year Commerce',
			},
			{
				name: 'Julian Widjaja',
				position: 'Webmaster',
				department: 'Marketing',
				image: EXECS_22_23[11],
				education: '3rd Year Science',
			},
			{
				name: 'Christopher Hadrian Wong',
				position: 'Webmaster',
				department: 'Marketing',
				image: EXECS_22_23[1],
				education: '3rd Year Science',
			},
			{
				name: 'Jena Arianto',
				position: 'Webmaster',
				department: 'Marketing',
				image: EXECS_22_23[7],
				education: '3rd Year Arts',
			},
		],
	},
};

export { BUTTONS, EXECUTIVES, VISION_MISSION };
